# Generated by Django 5.1.7 on 2026-01-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bugs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pre_condition", models.TextField(blank=True)),
                ("steps", models.TextField()),
                ("expected_result", models.TextField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Functional"),
                            (2, "Performance"),
                            (3, "Compatibility"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Executed"),
                            (1, "Executing"),
                            (2, "Passed"),
                            (3, "Failed"),
                            (4, "Blocked"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Executed"),
                            (1, "Executing"),
                            (2, "Passed"),
                            (3, "Failed"),
                            (4, "Blocked"),
                        ]
                    ),
                ),
                ("execute_time", models.DateTimeField(auto_now_add=True)),
                ("remark", models.TextField(blank=True)),
                (
                    "bug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="bugs.bug",
                    ),
                ),
            ],
        ),
    ]
