# Generated by Django 5.1.7 on 2026-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0004_remove_testcase_expected_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="execution_type",
            field=models.IntegerField(
                choices=[(1, "人工执行"), (2, "AI 自动化")],
                default=1,
                verbose_name="执行方式",
            ),
        ),
    ]
