# Generated by Django 5.1.7 on 2026-01-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0005_testcase_execution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseexecution",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "未执行"),
                    (1, "执行中"),
                    (2, "通过"),
                    (3, "失败"),
                    (4, "阻塞"),
                    (5, "已执行"),
                ],
                verbose_name="执行状态",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "未执行"),
                    (1, "执行中"),
                    (2, "通过"),
                    (3, "失败"),
                    (4, "阻塞"),
                    (5, "已执行"),
                ],
                default=0,
                verbose_name="执行状态",
            ),
        ),
    ]
