# Generated by Django 5.1.7 on 2026-01-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0003_alter_requirement_options_and_more"),
        ("testcases", "0006_alter_caseexecution_status_alter_testcase_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testcases",
                to="requirements.requirement",
                verbose_name="关联需求",
            ),
        ),
    ]
