# Generated by Django 5.1.7 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0010_testcasestep_guide_image_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasestep",
            name="transfer_file_base64",
            field=models.TextField(
                blank=True, null=True, verbose_name="传输文件(Base64)"
            ),
        ),
        migrations.AddField(
            model_name="testcasestep",
            name="transfer_file_content_type",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="传输文件类型"
            ),
        ),
        migrations.AddField(
            model_name="testcasestep",
            name="transfer_file_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="传输文件名"
            ),
        ),
        migrations.AddField(
            model_name="testcasestep",
            name="transfer_file_size",
            field=models.IntegerField(default=0, verbose_name="传输文件大小(字节)"),
        ),
    ]
