# Generated by Django 5.1.7 on 2026-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("reproduce_steps", models.TextField()),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "Major"),
                            (3, "Normal"),
                            (4, "Minor"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "New"),
                            (2, "Assigned"),
                            (3, "In Progress"),
                            (4, "Fixed"),
                            (5, "Verified"),
                            (6, "Closed"),
                            (7, "Reopened"),
                        ],
                        default=1,
                    ),
                ),
                ("affected_version", models.CharField(blank=True, max_length=50)),
                ("fixed_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BugAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bug_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
