# Generated by Django 5.1.7 on 2026-01-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_alter_projectmember_options_and_more"),
        ("requirements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requirement",
            options={"verbose_name": "需求", "verbose_name_plural": "需求"},
        ),
        migrations.AlterField(
            model_name="requirement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_requirements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="description",
            field=models.TextField(verbose_name="需求描述"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="expected_finish_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="预计完成时间"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "高"), (2, "中"), (3, "低")],
                default=2,
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "待评审"),
                    (2, "已确认"),
                    (3, "开发中"),
                    (4, "已完成"),
                    (5, "已关闭"),
                ],
                default=1,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="需求名称"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="type",
            field=models.IntegerField(
                choices=[(1, "功能需求"), (2, "非功能需求"), (3, "优化需求")],
                default=1,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="version",
            field=models.IntegerField(default=1, verbose_name="版本号"),
        ),
    ]
