# Generated by Django 5.2.10 on 2026-03-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testcases", "0013_testcasestep_smart_data_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UIAutoExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="结果汇总"),
                ),
                (
                    "stop_signal",
                    models.BooleanField(default=False, verbose_name="停止信号"),
                ),
                (
                    "pause_signal",
                    models.BooleanField(default=False, verbose_name="暂停信号"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_auto_executions",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI自动化执行记录",
                "verbose_name_plural": "UI自动化执行记录",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="UIAutoStepRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(verbose_name="步骤序号")),
                ("description", models.TextField(verbose_name="步骤描述")),
                (
                    "expected_result",
                    models.TextField(blank=True, verbose_name="预期结果"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="性能指标"),
                ),
                (
                    "screenshot_before",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uiauto/screenshots/",
                        verbose_name="执行前截图",
                    ),
                ),
                (
                    "screenshot_after",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uiauto/screenshots/",
                        verbose_name="执行后截图",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_records",
                        to="uiauto.uiautoexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testcases.testcasestep",
                        verbose_name="关联步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI自动化步骤记录",
                "verbose_name_plural": "UI自动化步骤记录",
                "ordering": ["step_number", "id"],
            },
        ),
    ]
