# Generated by Django 5.1.7 on 2026-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Functional"),
                            (2, "Non-functional"),
                            (3, "Optimization"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Reviewing"),
                            (2, "Confirmed"),
                            (3, "Dev"),
                            (4, "Done"),
                            (5, "Closed"),
                        ],
                        default=1,
                    ),
                ),
                ("expected_finish_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.IntegerField(default=1)),
            ],
        ),
    ]
