# Generated by Django 5.1.7 on 2026-01-10 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testcases", "0005_testcase_execution_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoTestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="结果汇总"),
                ),
                (
                    "stop_signal",
                    models.BooleanField(default=False, verbose_name="停止信号"),
                ),
                (
                    "pause_signal",
                    models.BooleanField(default=False, verbose_name="暂停信号"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_executions",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动化执行记录",
                "verbose_name_plural": "自动化执行记录",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AutoTestStepRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(verbose_name="步骤序号")),
                ("description", models.TextField(verbose_name="步骤描述")),
                ("ai_thought", models.TextField(blank=True, verbose_name="AI思考")),
                (
                    "action_script",
                    models.TextField(blank=True, verbose_name="执行脚本"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "screenshot_before",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="autotest/screenshots/",
                        verbose_name="执行前截图",
                    ),
                ),
                (
                    "screenshot_after",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="autotest/screenshots/",
                        verbose_name="执行后截图",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_records",
                        to="autotest.autotestexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testcases.testcasestep",
                        verbose_name="关联步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动化步骤记录",
                "verbose_name_plural": "自动化步骤记录",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="AutoTestNetworkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(verbose_name="URL")),
                ("method", models.CharField(max_length=10, verbose_name="Method")),
                ("status_code", models.IntegerField(verbose_name="Status Code")),
                ("request_data", models.TextField(blank=True, verbose_name="请求数据")),
                (
                    "response_data",
                    models.TextField(blank=True, verbose_name="响应数据"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "step_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_entries",
                        to="autotest.autoteststeprecord",
                        verbose_name="步骤记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "网络请求日志",
                "verbose_name_plural": "网络请求日志",
            },
        ),
    ]
