# Generated by Django 5.1.7 on 2026-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0004_alter_autotestexecution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoteststeprecord",
            name="metrics",
            field=models.JSONField(blank=True, default=dict, verbose_name="性能指标"),
        ),
    ]
