"""
Django settings for qa_platform project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _load_dotenv_file(path: Path):
    try:
        if not path.exists():
            return
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = (raw or "").strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = (k or "").strip()
            v = (v or "").strip().strip('"').strip("'")
            if not k:
                continue
            if k not in os.environ:
                os.environ[k] = v
    except Exception:
        return

_load_dotenv_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes", "y", "on")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "whitenoise.runserver_nostatic",
    "users",
    "projects",
    "requirements",
    "testcases",
    "bugs",
    "core",
    "ai_assistant",
    "autotest.apps.AutotestConfig",
    "uiauto.apps.UIAutoConfig",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "qa_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.feature_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "qa_platform.wsgi.application"


def _env_str(name: str, default: str = "") -> str:
    v = os.getenv(name, None)
    if v is None:
        return str(default)
    return str(v).strip()


def _env_int(name: str, default: int) -> int:
    v = os.getenv(name, "")
    if v is None or v == "":
        return int(default)
    try:
        return int(str(v).strip())
    except Exception:
        return int(default)


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.getenv(name, "")
    if v is None or v == "":
        return bool(default)
    return str(v).strip().lower() in ("1", "true", "yes", "y", "on")


def _db_config_from_env() -> dict:
    engine = _env_str("DJANGO_DB_ENGINE", "").lower()
    if engine in ("postgres", "postgresql", "psql"):
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _env_str("DJANGO_DB_NAME", "qa_platform"),
            "USER": _env_str("DJANGO_DB_USER", "qa_platform"),
            "PASSWORD": _env_str("DJANGO_DB_PASSWORD", "qa_platform"),
            "HOST": _env_str("DJANGO_DB_HOST", "127.0.0.1"),
            "PORT": _env_str("DJANGO_DB_PORT", "5432"),
            "CONN_MAX_AGE": _env_int("DJANGO_DB_CONN_MAX_AGE", 60),
        }
    if engine in ("mysql", "mariadb"):
        return {
            "ENGINE": "django.db.backends.mysql",
            "NAME": _env_str("DJANGO_DB_NAME", "qa_platform"),
            "USER": _env_str("DJANGO_DB_USER", "qa_platform"),
            "PASSWORD": _env_str("DJANGO_DB_PASSWORD", "qa_platform"),
            "HOST": _env_str("DJANGO_DB_HOST", "127.0.0.1"),
            "PORT": _env_str("DJANGO_DB_PORT", "3306"),
            "CONN_MAX_AGE": _env_int("DJANGO_DB_CONN_MAX_AGE", 60),
        }
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": _env_int("DJANGO_DB_SQLITE_TIMEOUT", 30),
            "check_same_thread": False,
        },
        "CONN_MAX_AGE": 0,
    }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {"default": _db_config_from_env()}
try:
    from qa_platform.sqlite_pragma import setup_sqlite_pragmas  # noqa: F401
except Exception:
    pass

FEATURE_HIDE_BATCH_EXEC = _env_bool("FEATURE_HIDE_BATCH_EXEC", False)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AI Service Configuration
AI_QWEN_API_KEY = os.getenv("AI_QWEN_API_KEY", "")
AI_QWEN_BASE_URL = os.getenv("AI_QWEN_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1")
AI_QWEN_MODEL = os.getenv("AI_QWEN_MODEL", "qwen2.5-vl-72b-instruct")
AI_QWEN_OCR_MODEL = os.getenv("AI_QWEN_OCR_MODEL", "")

AI_DEEPSEEK_API_KEY = os.getenv("AI_DEEPSEEK_API_KEY", "")
AI_DEEPSEEK_BASE_URL = os.getenv("AI_DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1")
AI_DEEPSEEK_MODEL = os.getenv("AI_DEEPSEEK_MODEL", "deepseek-chat")

AI_REVIEW_API_KEY = os.getenv("AI_REVIEW_API_KEY", "")
AI_REVIEW_BASE_URL = os.getenv("AI_REVIEW_BASE_URL", "https://api.deepseek.com/v1")
AI_REVIEW_MODEL = os.getenv("AI_REVIEW_MODEL", "deepseek-chat")

SERVE_MEDIA = _env_bool("DJANGO_SERVE_MEDIA", False)


AI_EXEC_STEP_WAIT_MS = _env_int("AI_EXEC_STEP_WAIT_MS", 500)
AI_EXEC_NETWORKIDLE_TIMEOUT_MS = _env_int("AI_EXEC_NETWORKIDLE_TIMEOUT_MS", 2500)
AI_EXEC_RETRY_SLEEP_MS = _env_int("AI_EXEC_RETRY_SLEEP_MS", 600)
AI_EXEC_MAX_RETRIES = _env_int("AI_EXEC_MAX_RETRIES", 4)
AI_EXEC_SCREENSHOT_MODE = (os.getenv("AI_EXEC_SCREENSHOT_MODE", "all") or "all").strip().lower()
if AI_EXEC_SCREENSHOT_MODE not in ("all", "failed"):
    AI_EXEC_SCREENSHOT_MODE = "all"
if DEBUG and AI_EXEC_SCREENSHOT_MODE == "failed":
    AI_EXEC_SCREENSHOT_MODE = "all"
AI_EXEC_TOAST_OCR_ENABLED = _env_bool("AI_EXEC_TOAST_OCR_ENABLED", True)
AI_EXEC_TOAST_OCR_TIMEOUT_S = _env_int("AI_EXEC_TOAST_OCR_TIMEOUT_S", 8)
AI_EXEC_TOAST_OCR_MIN_INTERVAL_S = _env_int("AI_EXEC_TOAST_OCR_MIN_INTERVAL_S", 2)
AI_EXEC_CONSOLE_POLL_MS = _env_int("AI_EXEC_CONSOLE_POLL_MS", 1000)
AI_EXEC_STOP_CHECK_MIN_STEP = _env_int("AI_EXEC_STOP_CHECK_MIN_STEP", 5)
AI_EXEC_SUBMIT_OBSERVE_WAIT_MS = _env_int("AI_EXEC_SUBMIT_OBSERVE_WAIT_MS", 2500)
AI_EXEC_EVIDENCE_MAXLEN = _env_int("AI_EXEC_EVIDENCE_MAXLEN", 240)
AI_EXEC_NON_BLOCKING_NOTE_MAX = _env_int("AI_EXEC_NON_BLOCKING_NOTE_MAX", 20)
AI_EXEC_CI_TOKEN = (os.getenv("AI_EXEC_CI_TOKEN", "") or "").strip()
AI_EXEC_HEADLESS = _env_bool("AI_EXEC_HEADLESS", True)
AI_EXEC_ENGINE = (os.getenv("AI_EXEC_ENGINE", "browser_use") or "browser_use").strip().lower()
AI_EXEC_AGENT_STEP_TIMEOUT_S = _env_int("AI_EXEC_AGENT_STEP_TIMEOUT_S", 0)
AI_EXEC_AGENT_TOTAL_TIMEOUT_S = _env_int("AI_EXEC_AGENT_TOTAL_TIMEOUT_S", 1800)
AI_EXEC_ESCALATE_NON_BLOCKING_ON_STEP_DONE = _env_bool("AI_EXEC_ESCALATE_NON_BLOCKING_ON_STEP_DONE", False)
AI_EXEC_AGENT_MIN_STEPS = _env_int("AI_EXEC_AGENT_MIN_STEPS", 10)
AI_EXEC_AGENT_STEPS_PER_CASE_STEP = _env_int("AI_EXEC_AGENT_STEPS_PER_CASE_STEP", 10)
AI_EXEC_AGENT_MAX_STEPS = _env_int("AI_EXEC_AGENT_MAX_STEPS", 280)
AI_EXEC_PREFLIGHT_TIMEOUT_MS = _env_int("AI_EXEC_PREFLIGHT_TIMEOUT_MS", 60000)
AI_EXEC_CHROME_USE_NEW_HEADLESS = _env_bool("AI_EXEC_CHROME_USE_NEW_HEADLESS", True)
AI_EXEC_CHROME_DISABLE_BACKGROUND_NETWORKING = _env_bool("AI_EXEC_CHROME_DISABLE_BACKGROUND_NETWORKING", False)
AI_EXEC_CHROME_IGNORE_CERT_ERRORS = _env_bool("AI_EXEC_CHROME_IGNORE_CERT_ERRORS", False)
AI_EXEC_HEADFUL_FALLBACK_ON_NETWORK_ERROR = _env_bool("AI_EXEC_HEADFUL_FALLBACK_ON_NETWORK_ERROR", True)
AI_EXEC_PAGINATION_STEPS_PER_PAGE = _env_int("AI_EXEC_PAGINATION_STEPS_PER_PAGE", 10)

AI_TESTCASE_ENGINE = (os.getenv("AI_TESTCASE_ENGINE", "legacy") or "legacy").strip().lower()

AI_PDF_PAGEWISE_MODE = (os.getenv("AI_PDF_PAGEWISE_MODE", "balanced") or "balanced").strip().lower()
AI_PDF_PAGEWISE_RENDER_SCALE = float(os.getenv("AI_PDF_PAGEWISE_RENDER_SCALE", "1.4") or "1.4")
AI_PDF_PAGEWISE_IMAGE_MAX_DIM = _env_int("AI_PDF_PAGEWISE_IMAGE_MAX_DIM", 1400)
AI_PDF_PAGEWISE_SKIP_LOW_VALUE = _env_bool("AI_PDF_PAGEWISE_SKIP_LOW_VALUE", True)
AI_PDF_PAGEWISE_MAX_PAGES = _env_int("AI_PDF_PAGEWISE_MAX_PAGES", 80)
AI_PDF_PAGEWISE_OCR = _env_bool("AI_PDF_PAGEWISE_OCR", False)
