# Generated by Django 5.1.7 on 2026-01-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0002_initial"),
        ("projects", "0002_initial"),
        ("testcases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bug",
            options={"verbose_name": "缺陷", "verbose_name_plural": "缺陷"},
        ),
        migrations.AlterModelOptions(
            name="bugattachment",
            options={"verbose_name": "Bug附件", "verbose_name_plural": "Bug附件"},
        ),
        migrations.AlterField(
            model_name="bug",
            name="affected_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="影响版本"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bugs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指派给",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bugs",
                to="testcases.testcase",
                verbose_name="关联用例",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bugs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="description",
            field=models.TextField(verbose_name="问题描述"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="fixed_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="修复版本"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "高"), (2, "中"), (3, "低")],
                default=2,
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bugs",
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="reproduce_steps",
            field=models.TextField(verbose_name="复现步骤"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="severity",
            field=models.IntegerField(
                choices=[(1, "致命"), (2, "严重"), (3, "一般"), (4, "轻微")],
                default=3,
                verbose_name="严重程度",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "新建"),
                    (2, "已分配"),
                    (3, "开发中"),
                    (4, "已修复"),
                    (5, "待验证"),
                    (6, "已关闭"),
                    (7, "重开"),
                ],
                default=1,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Bug标题"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="bugattachment",
            name="bug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="bugs.bug",
                verbose_name="所属Bug",
            ),
        ),
        migrations.AlterField(
            model_name="bugattachment",
            name="file",
            field=models.FileField(upload_to="bug_attachments/", verbose_name="文件"),
        ),
        migrations.AlterField(
            model_name="bugattachment",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
        ),
    ]
