from django.urls import path
from . import views

urlpatterns = [
    path('run/<int:case_id>/', views.run_test, name='run_test'),
    path('batch-run/', views.batch_run_test, name='batch_run_test'),
    path('pause/<int:execution_id>/', views.pause_test, name='pause_test'),
    path('resume/<int:execution_id>/', views.resume_test, name='resume_test'),
    path('stop/<int:execution_id>/', views.stop_test, name='stop_test'),
    path('status/<int:execution_id>/', views.get_execution_status, name='get_execution_status'),
    path('console/<int:execution_id>/', views.console, name='console'),
    path('reports/', views.report_list, name='report_list'),
    path('report/<int:execution_id>/', views.report_detail, name='report_detail'),
    path('report/<int:execution_id>/export.json', views.report_export_json, name='report_export_json'),
    path('report/<int:execution_id>/export.md', views.report_export_md, name='report_export_md'),
    path('report/<int:execution_id>/share', views.report_share_create, name='report_share_create'),
    path('report/share/<uuid:token>/', views.report_shared, name='report_shared'),
    path('execute-direct/', views.execute_direct, name='execute_direct'),
    path('ai-direct/', views.ai_direct_execute, name='ai_direct_execute'),
    path('upload-sandbox/', views.upload_sandbox, name='upload_sandbox'),
    path('ci/trigger/', views.ci_trigger, name='ci_trigger'),
    path('ci/status/<int:execution_id>/', views.ci_status, name='ci_status'),
    path('cicd/', views.cicd_page, name='cicd_page'),
    path('cicd/token/rotate/', views.cicd_token_rotate, name='cicd_token_rotate'),
    path('record/', views.playwright_record_page, name='playwright_record_page'),
    path('record/download/<str:kind>/', views.playwright_record_download, name='playwright_record_download'),
    path('record/session/new/', views.recorder_session_new, name='recorder_session_new'),
    path('record/session/<str:token>/event/', views.recorder_session_event, name='recorder_session_event'),
    path('record/session/<str:token>/poll/', views.recorder_session_poll, name='recorder_session_poll'),
    path('record/session/<str:token>/export/', views.recorder_session_export, name='recorder_session_export'),
    path('record/session/<str:token>/commands/set/', views.recorder_session_commands_set, name='recorder_session_commands_set'),
    path('record/session/<str:token>/commands/poll/', views.recorder_session_commands_poll, name='recorder_session_commands_poll'),
    path('record/session/<str:token>/save-case/', views.recorder_session_save_case, name='recorder_session_save_case'),
    path('recorder/', views.recorder_import_page, name='recorder_import_page'),
    path('recorder/import/', views.recorder_import_submit, name='recorder_import_submit'),
    path('schedules/', views.schedule_list, name='autotest_schedule_list'),
    path('schedules/new/', views.schedule_create, name='autotest_schedule_create'),
    path('schedules/<int:schedule_id>/edit/', views.schedule_edit, name='autotest_schedule_edit'),
    path('schedules/<int:schedule_id>/toggle/', views.schedule_toggle, name='autotest_schedule_toggle'),
    path('schedules/<int:schedule_id>/delete/', views.schedule_delete, name='autotest_schedule_delete'),
    path('schedules/<int:schedule_id>/run-now/', views.schedule_run_now, name='autotest_schedule_run_now'),
]
