# Generated by Django 5.1.7 on 2026-01-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0003_alter_bug_options_alter_bugattachment_options_and_more"),
        ("projects", "0003_alter_project_options_alter_projectmember_options_and_more"),
        ("requirements", "0003_alter_requirement_options_and_more"),
        ("testcases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseexecution",
            options={"verbose_name": "执行记录", "verbose_name_plural": "执行记录"},
        ),
        migrations.AlterModelOptions(
            name="testcase",
            options={"verbose_name": "测试用例", "verbose_name_plural": "测试用例"},
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="bug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="bugs.bug",
                verbose_name="关联Bug",
            ),
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="testcases.testcase",
                verbose_name="用例",
            ),
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="execute_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="executor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="执行人",
            ),
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="remark",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="caseexecution",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "未执行"),
                    (1, "执行中"),
                    (2, "通过"),
                    (3, "失败"),
                    (4, "阻塞"),
                ],
                verbose_name="执行状态",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="expected_result",
            field=models.TextField(verbose_name="预期结果"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="pre_condition",
            field=models.TextField(blank=True, verbose_name="前置条件"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "高"), (2, "中"), (3, "低")],
                default=2,
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="requirements.requirement",
                verbose_name="关联需求",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "未执行"),
                    (1, "执行中"),
                    (2, "通过"),
                    (3, "失败"),
                    (4, "阻塞"),
                ],
                default=0,
                verbose_name="执行状态",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="steps",
            field=models.TextField(verbose_name="操作步骤"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="title",
            field=models.CharField(max_length=200, verbose_name="用例标题"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="type",
            field=models.IntegerField(
                choices=[(1, "功能用例"), (2, "性能用例"), (3, "兼容性用例")],
                default=1,
                verbose_name="类型",
            ),
        ),
    ]
