# Generated by Django 5.1.7 on 2026-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0008_testcase_case_mode_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasestep",
            name="guide_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testcase_step_guides/%Y/%m/%d/",
                verbose_name="参考截图",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="case_mode",
            field=models.CharField(
                choices=[("normal", "普通用例"), ("advanced", "高级用例")],
                default="normal",
                max_length=20,
                verbose_name="用例模式",
            ),
        ),
    ]
