# Generated by Django 5.1.7 on 2026-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0009_testcasestep_guide_image_alter_testcase_case_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasestep",
            name="guide_image_base64",
            field=models.TextField(
                blank=True, null=True, verbose_name="参考截图(Base64)"
            ),
        ),
    ]
