# Generated by Django 5.1.7 on 2026-01-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "项目", "verbose_name_plural": "项目"},
        ),
        migrations.AlterModelOptions(
            name="projectmember",
            options={"verbose_name": "项目成员", "verbose_name_plural": "项目成员"},
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="项目描述"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="负责人",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[(1, "待启动"), (2, "进行中"), (3, "已暂停"), (4, "已结束")],
                default=1,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="join_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships",
                to="auth.group",
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
