# Generated by Django 5.1.7 on 2026-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_alter_projectmember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="base_url",
            field=models.URLField(blank=True, default="", verbose_name="项目URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="history_requirements",
            field=models.TextField(blank=True, default="", verbose_name="历史需求"),
        ),
        migrations.AddField(
            model_name="project",
            name="knowledge_base",
            field=models.TextField(blank=True, default="", verbose_name="项目资料库"),
        ),
        migrations.AddField(
            model_name="project",
            name="test_accounts",
            field=models.TextField(blank=True, default="", verbose_name="测试账号"),
        ),
    ]
