# Generated by Django 5.1.7 on 2026-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_base_url_project_history_requirements_and_more"),
        ("users", "0002_usergroup_usergroupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="shared_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_user_groups",
                to="projects.project",
                verbose_name="共享项目",
            ),
        ),
    ]
